version: '3'
services:
  checker-daemon:
     build: .
     command: >
      sh -c "npx prisma generate &&
             npx prisma db push &&
             npm start"
     volumes:
       - .:/usr/app
       - /usr/app/node_modules
     restart: always
     networks:
       - default
       - postgres

networks:
  postgres:
    external: true
