version: '3'
services:
  checker-daemon:
     build: .
     command: >
      sh -c "npx prisma db push &&
             npm start"
     env_file:
       - .env
     user: node
     security_opt:
       - no-new-privileges:true
     restart: always
     networks:
       - default
       - postgres

networks:
  postgres:
    external: true
